version: '3.9'

services:
  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - 2379:2379
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
  mysql:
    image: 'mysql:latest'
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=douyin
      - MYSQL_USER=douyin
      - MYSQL_PASSWORD=douyin
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6388:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
  api:
    build:
      context: .
      dockerfile: ./cmd/api/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      redis:
        condition: service_healthy
      etcd:
        condition: service_started
      jaeger:
        condition: service_started
  user:
    build:
      context: .
      dockerfile: ./cmd/user/Dockerfile
    network_mode: host
    depends_on:
      mysql:
        condition: service_healthy
      etcd:
        condition: service_started
      jaeger:
        condition: service_started
  video:
    build:
      context: .
      dockerfile: ./cmd/video/Dockerfile
    network_mode: host
    depends_on:
      mysql:
        condition: service_healthy
      etcd:
        condition: service_started
      jaeger:
        condition: service_started
