Server:
  RunMode: debug
  HttpPort: :8080
  RedisPort: :6379
  Timeout: 86400 #seconds
  EtcdAddress: 127.0.0.1:2379
  FeedCount: 5

OSS:
  KeyID: your key id
  KeySecret: your key secret
  Endpoint: your endpoint

Database:
  DBType: mysql
  UserName: root #your username
  Password: rootroot #your password
  Host: 127.0.0.1:3306
  DBName: douyin
  Charset: utf8mb4
  ParseTime: True

JWT:
  Secret: your secret
  Expires: 24 #hours
