// Code generated by Kitex v0.3.1. DO NOT EDIT.
package videoservice

import (
	"github.com/cloudwego/kitex/server"
	"simple-douyin/kitex_gen/videoproto"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler videoproto.VideoService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
