// Code generated by Kitex v0.3.1. DO NOT EDIT.

package userservice

import (
	"context"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
	"simple-douyin/cmd/user/kitex_gen/userproto"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateUser(ctx context.Context, Req *userproto.CreateUserReq, callOptions ...callopt.Option) (r *userproto.CreateUserResp, err error)
	UpdateUser(ctx context.Context, Req *userproto.UpdateUserReq, callOptions ...callopt.Option) (r *userproto.UpdateUserResp, err error)
	GetUserById(ctx context.Context, Req *userproto.GetUserByIdReq, callOptions ...callopt.Option) (r *userproto.GetUserByIdResp, err error)
	GetUserByEmail(ctx context.Context, Req *userproto.GetUserByEmailReq, callOptions ...callopt.Option) (r *userproto.GetUserByEmailResp, err error)
	CheckPassword(ctx context.Context, Req *userproto.CheckPasswordReq, callOptions ...callopt.Option) (r *userproto.CheckPasswordResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) CreateUser(ctx context.Context, Req *userproto.CreateUserReq, callOptions ...callopt.Option) (r *userproto.CreateUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateUser(ctx, Req)
}

func (p *kUserServiceClient) UpdateUser(ctx context.Context, Req *userproto.UpdateUserReq, callOptions ...callopt.Option) (r *userproto.UpdateUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateUser(ctx, Req)
}

func (p *kUserServiceClient) GetUserById(ctx context.Context, Req *userproto.GetUserByIdReq, callOptions ...callopt.Option) (r *userproto.GetUserByIdResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserById(ctx, Req)
}

func (p *kUserServiceClient) GetUserByEmail(ctx context.Context, Req *userproto.GetUserByEmailReq, callOptions ...callopt.Option) (r *userproto.GetUserByEmailResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserByEmail(ctx, Req)
}

func (p *kUserServiceClient) CheckPassword(ctx context.Context, Req *userproto.CheckPasswordReq, callOptions ...callopt.Option) (r *userproto.CheckPasswordResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CheckPassword(ctx, Req)
}
