// Code generated by Kitex v0.3.1. DO NOT EDIT.

package userservice

import (
	"context"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
	"simple-douyin/kitex_gen/userproto"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateUser(ctx context.Context, Req *userproto.CreateUserReq, callOptions ...callopt.Option) (r *userproto.CreateUserResp, err error)
	GetUser(ctx context.Context, Req *userproto.GetUserReq, callOptions ...callopt.Option) (r *userproto.GetUserResp, err error)
	CheckUser(ctx context.Context, Req *userproto.CheckUserReq, callOptions ...callopt.Option) (r *userproto.CheckUserResp, err error)
	FollowUser(ctx context.Context, Req *userproto.FollowUserReq, callOptions ...callopt.Option) (r *userproto.FollowUserResp, err error)
	UnFollowUser(ctx context.Context, Req *userproto.UnFollowUserReq, callOptions ...callopt.Option) (r *userproto.UnFollowUserResp, err error)
	GetUserRelations(ctx context.Context, Req *userproto.GetUserRelationsReq, callOptions ...callopt.Option) (r *userproto.GetUserRelationsResp, err error)
	GetWhetherBeFollowed(ctx context.Context, Req *userproto.GetWhetherBeFollowedReq, callOptions ...callopt.Option) (r *userproto.GetWhetherBeFollowedResp, err error)
	GetFollowList(ctx context.Context, Req *userproto.GetFollowListReq, callOptions ...callopt.Option) (r *userproto.GetFollowListResp, err error)
	GetFanList(ctx context.Context, Req *userproto.GetFanListReq, callOptions ...callopt.Option) (r *userproto.GetFanListResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) CreateUser(ctx context.Context, Req *userproto.CreateUserReq, callOptions ...callopt.Option) (r *userproto.CreateUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateUser(ctx, Req)
}

func (p *kUserServiceClient) GetUser(ctx context.Context, Req *userproto.GetUserReq, callOptions ...callopt.Option) (r *userproto.GetUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUser(ctx, Req)
}

func (p *kUserServiceClient) CheckUser(ctx context.Context, Req *userproto.CheckUserReq, callOptions ...callopt.Option) (r *userproto.CheckUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CheckUser(ctx, Req)
}

func (p *kUserServiceClient) FollowUser(ctx context.Context, Req *userproto.FollowUserReq, callOptions ...callopt.Option) (r *userproto.FollowUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowUser(ctx, Req)
}

func (p *kUserServiceClient) UnFollowUser(ctx context.Context, Req *userproto.UnFollowUserReq, callOptions ...callopt.Option) (r *userproto.UnFollowUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UnFollowUser(ctx, Req)
}

func (p *kUserServiceClient) GetUserRelations(ctx context.Context, Req *userproto.GetUserRelationsReq, callOptions ...callopt.Option) (r *userproto.GetUserRelationsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserRelations(ctx, Req)
}

func (p *kUserServiceClient) GetWhetherBeFollowed(ctx context.Context, Req *userproto.GetWhetherBeFollowedReq, callOptions ...callopt.Option) (r *userproto.GetWhetherBeFollowedResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetWhetherBeFollowed(ctx, Req)
}

func (p *kUserServiceClient) GetFollowList(ctx context.Context, Req *userproto.GetFollowListReq, callOptions ...callopt.Option) (r *userproto.GetFollowListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFollowList(ctx, Req)
}

func (p *kUserServiceClient) GetFanList(ctx context.Context, Req *userproto.GetFanListReq, callOptions ...callopt.Option) (r *userproto.GetFanListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFanList(ctx, Req)
}
